# compiler settings
VC=valac
VCFLAGS=--pkg gtk+-3.0

# name for each output (and file)
ACTIONBAR=actionbar
BOX=box
BUTTONBOX=buttonbox
BUTTON=button
CHECKBUTTON=checkbutton
COMBOBOXTEXT=comboboxtext
COMBOBOX=combobox
ENTRYBUFFER=entrybuffer
ENTRYCOMPLETION=entrycompletion
ENTRY=entry
FILECHOOSERBUTTON=filechooserbutton
FLOWBOX=flowbox
FONTBUTTON=fontbutton
GRID=grid
LABEL=label
LISTBOX=listbox
NOTEBOOK=notebook
PANED=paned
RADIOBUTTON=radiobutton
SCALE=scale
SEARCHENTRY=searchentry
SEPARATOR=separator
SOURCEVIEW=sourceview
SPINBUTTON=spinbutton
SPINNER=spinner
STACKSIDEBAR=stacksidebar
STACKSWITCHER=stackswitcher
STACK=stack
TOGGLEBUTTON=togglebutton

.PHONY: all clean

all: $(ACTIONBAR) $(BOX) $(BUTTONBOX) $(BUTTON) $(CHECKBUTTON) $(COMBOBOXTEXT)\
$(COMBOBOX) $(ENTRYBUFFER) $(ENTRYCOMPLETION) $(ENTRY) $(FILECHOOSERBUTTON)\
$(FLOWBOX) $(FONTBUTTON) $(GRID) $(LABEL) $(LISTBOX) $(NOTEBOOK) $(PANED)\
$(RADIOBUTTON) $(SCALE) $(SEARCHENTRY) $(SEPARATOR) $(SPINBUTTON) $(SPINNER)\
$(STACKSIDEBAR) $(STACKSWITCHER) $(STACK) $(TOGGLEBUTTON)

$(ACTIONBAR): $(ACTIONBAR).vala
	$(VC) $(VCFLAGS) $(ACTIONBAR).vala

$(BOX): $(BOX).vala
	$(VC) $(VCFLAGS) $(BOX).vala

$(BUTTONBOX): $(BUTTONBOX).vala
	$(VC) $(VCFLAGS) $(BUTTONBOX).vala

$(BUTTON): $(BUTTON).vala
	$(VC) $(VCFLAGS) $(BUTTON).vala

$(CHECKBUTTON): $(CHECKBUTTON).vala
	$(VC) $(VCFLAGS) $(CHECKBUTTON).vala

$(COMBOBOXTEXT): $(COMBOBOXTEXT).vala
	$(VC) $(VCFLAGS) $(COMBOBOXTEXT).vala

$(COMBOBOX): $(COMBOBOX).vala
	$(VC) $(VCFLAGS) $(COMBOBOX).vala

$(ENTRYBUFFER): $(ENTRYBUFFER).vala
	$(VC) $(VCFLAGS) $(ENTRYBUFFER).vala

$(ENTRYCOMPLETION): $(ENTRYCOMPLETION).vala
	$(VC) $(VCFLAGS) $(ENTRYCOMPLETION).vala

$(ENTRY): $(ENTRY).vala
	$(VC) $(VCFLAGS) $(ENTRY).vala

$(FILECHOOSERBUTTON): $(FILECHOOSERBUTTON).vala
	$(VC) $(VCFLAGS) $(FILECHOOSERBUTTON).vala

$(FLOWBOX): $(FLOWBOX).vala
	$(VC) $(VCFLAGS) $(FLOWBOX).vala

$(FONTBUTTON): $(FONTBUTTON).vala
	$(VC) $(VCFLAGS) $(FONTBUTTON).vala

$(GRID): $(GRID).vala
	$(VC) $(VCFLAGS) $(GRID).vala

$(LABEL): $(LABEL).vala
	$(VC) $(VCFLAGS) $(LABEL).vala

$(LISTBOX): $(LISTBOX).vala
	$(VC) $(VCFLAGS) $(LISTBOX).vala

$(NOTEBOOK): $(NOTEBOOK).vala
	$(VC) $(VCFLAGS) $(NOTEBOOK).vala

$(PANED): $(PANED).vala
	$(VC) $(VCFLAGS) $(PANED).vala

$(RADIOBUTTON): $(RADIOBUTTON).vala
	$(VC) $(VCFLAGS) $(RADIOBUTTON).vala

$(SCALE): $(SCALE).vala
	$(VC) $(VCFLAGS) $(SCALE).vala

$(SEARCHENTRY): $(SEARCHENTRY).vala
	$(VC) $(VCFLAGS) $(SEARCHENTRY).vala

$(SEPARATOR): $(SEPARATOR).vala
	$(VC) $(VCFLAGS) $(SEPARATOR).vala

$(SOURCEVIEW): $(SOURCEVIEW).vala
	$(VC) $(VCFLAGS) $(SOURCEVIEW).vala

$(SPINBUTTON): $(SPINBUTTON).vala
	$(VC) $(VCFLAGS) $(SPINBUTTON).vala

$(SPINNER): $(SPINNER).vala
	$(VC) $(VCFLAGS) $(SPINNER).vala

$(STACKSIDEBAR): $(STACKSIDEBAR).vala
	$(VC) $(VCFLAGS) $(STACKSIDEBAR).vala

$(STACKSWITCHER): $(STACKSWITCHER).vala
	$(VC) $(VCFLAGS) $(STACKSWITCHER).vala

$(STACK): $(STACK).vala
	$(VC) $(VCFLAGS) $(STACK).vala

$(TOGGLEBUTTON): $(TOGGLEBUTTON).vala
	$(VC) $(VCFLAGS) $(TOGGLEBUTTON).vala

clean:
	@rm -f $(ACTIONBAR) $(BOX) $(BUTTONBOX) $(BUTTON) $(CHECKBUTTON) $(COMBOBOXTEXT) \
	$(COMBOBOX) $(ENTRYBUFFER) $(ENTRYCOMPLETION) $(ENTRY) $(FILECHOOSERBUTTON) \
	$(FLOWBOX) $(FONTBUTTON) $(GRID) $(LABEL) $(LISTBOX) $(NOTEBOOK) $(PANED) \
	$(RADIOBUTTON) $(SCALE) $(SEARCHENTRY) $(SEPARATOR) $(SPINBUTTON) $(SPINNER) \
	$(STACKSIDEBAR) $(STACKSWITCHER) $(STACK) $(TOGGLEBUTTON)

